name: Run benchmark
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install TytoDB
      run: |
        mkdir -p ~/program
        git clone "https://github.com/FeatheredSystems/TytoDB" ~/program/TytoDB
        
    - name: Install Rust Nightly Toolchain
      uses: dtolnay/rust-toolchain@nightly
      
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Install liburing-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y liburing-dev
        
    - name: Install liburing from source
      run: |
        cd ~
        git clone https://github.com/axboe/liburing
        cd liburing
        ./configure
        make
        sudo make install
        sudo ldconfig
        
    - name: Build TytoDB
      run: curl -fsSL https://tytodb.pages.dev/installer.sh | bash
    - name: Build benchmark
      run: cargo build --release
      
    - name: Run benchmark
      run: |
        cargo run --release
        
    - name: Stop TytoDB
      if: always()
      run: |
        if [ -f ~/program/TytoDB/tytodb.pid ]; then
          PID=$(cat ~/program/TytoDB/tytodb.pid)
          if kill -0 $PID 2>/dev/null; then
            kill $PID
            echo "Stopped TytoDB (PID: $PID)"
          fi
        fi
        pkill -f "cargo.*TytoDB\|TytoDB" || true
        
    - name: Show running processes
      if: always()
      run: |
        echo "=== Final Process Check ==="
        ps aux | grep -E "(cargo|TytoDB)" || echo "No TytoDB processes found"
