name: Run benchmark
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install TytoDB
      run: |
        mkdir -p ~/program
        git clone "https://github.com/FeatheredSystems/TytoDB" ~/program/TytoDB
        
    - name: Install Rust Nightly Toolchain
      uses: dtolnay/rust-toolchain@nightly
      
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Install liburing-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y liburing-dev netcat-openbsd
        
    - name: Install liburing from source
      run: |
        cd ~
        git clone https://github.com/axboe/liburing
        cd liburing
        ./configure
        make
        sudo make install
        sudo ldconfig
        
    - name: Install TytoDB binary
      run: curl -fsSL https://raw.githubusercontent.com/FeatheredSystems/TytoDB-Installer/refs/heads/master/installer.sh | bash
      
    - name: Start TytoDB in background
      run: |
        echo "Starting TytoDB..."
        tytodb &
        echo $! > tytodb.pid
        
    - name: Wait for TytoDB to be ready
      run: |
        echo "Waiting for TytoDB to start..."
        for i in {1..30}; do
          if nc -z 127.0.0.1 4287 2>/dev/null; then
            echo "TytoDB is listening on port 4287"
            sleep 3
            break
          fi
          echo "Waiting... ($i/30)"
          sleep 2
        done
        
        # Verify it's listening
        if ! nc -z 127.0.0.1 4287 2>/dev/null; then
          echo "TytoDB failed to start listening on port 4287"
          echo "Current processes:"
          ps aux | grep -E "tytodb" || true
          exit 1
        fi
        echo "TytoDB is ready for benchmarking"
        
    - name: Build benchmark
      run: cargo build --release
      
    - name: Run benchmark
      run: cargo run --release
        
    - name: Stop TytoDB
      if: always()
      run: |
        echo "Stopping TytoDB..."
        if [ -f tytodb.pid ]; then
          PID=$(cat tytodb.pid)
          if kill -0 $PID 2>/dev/null; then
            kill $PID
            echo "Stopped TytoDB (PID: $PID)"
          fi
          rm -f tytodb.pid
        fi
        pkill -f "tytodb" || true
        
    - name: Show final processes
      if: always()
      run: |
        echo "=== Final Process Check ==="
        ps aux | grep -E "tytodb" || echo "No TytoDB processes found"